#ifndef SPEAKER_TOGGLE_CONF_H
#define SPEAKER_TOGGLE_CONF_H

static const char speaker_on_conf[] =
    "#\n"
    "# Audio policy configuration for generic device builds (goldfish audio HAL - emulator)\n"
    "#\n"
    "\n"
    "# Global configuration section: lists input and output devices always present on the device\n"
    "# as well as the output device selected by default.\n"
    "# Devices are designated by a string that corresponds to the enum in audio.h\n"
    "\n"
    "global_configuration {\n"
    "  attached_output_devices AUDIO_DEVICE_OUT_SPEAKER|AUDIO_DEVICE_OUT_EARPIECE\n"
    "  default_output_device AUDIO_DEVICE_OUT_SPEAKER\n"
    "  attached_input_devices AUDIO_DEVICE_IN_BUILTIN_MIC\n"
    "}\n"
    "\n"
    "# audio hardware module section: contains descriptors for all audio hw modules present on the\n"
    "# device. Each hw module node is named after the corresponding hw module library base name.\n"
    "# For instance, \"primary\" corresponds to audio.primary.<device>.so.\n"
    "# The \"primary\" module is mandatory and must include at least one output with\n"
    "# AUDIO_OUTPUT_FLAG_PRIMARY flag.\n"
    "# Each module descriptor contains one or more output profile descriptors and zero or more\n"
    "# input profile descriptors. Each profile lists all the parameters supported by a given output\n"
    "# or input stream category.\n"
    "# The \"channel_masks\", \"formats\", \"devices\" and \"flags\" are specified using strings corresponding\n"
    "# to enums in audio.h and audio_policy.h. They are concatenated by use of \"|\" without space or \"\\n\".\n"
    "\n"
    "audio_hw_modules {\n"
    "  primary {\n"
    "    outputs {\n"
    "      primary {\n"
    "        sampling_rates 44100\n"
    "        channel_masks AUDIO_CHANNEL_OUT_STEREO\n"
    "        formats AUDIO_FORMAT_PCM_16_BIT\n"
    "        devices AUDIO_DEVICE_OUT_EARPIECE|AUDIO_DEVICE_OUT_SPEAKER|AUDIO_DEVICE_OUT_WIRED_HEADSET|AUDIO_DEVICE_OUT_WIRED_HEADPHONE|AUDIO_DEVICE_OUT_AUX_DIGITAL|AUDIO_DEVICE_OUT_ANLG_DOCK_HEADSET|AUDIO_DEVICE_OUT_DGTL_DOCK_HEADSET|AUDIO_DEVICE_OUT_ALL_SCO|AUDIO_DEVICE_OUT_FM_TX|AUDIO_DEVICE_OUT_DEFAULT\n"
    "        flags AUDIO_OUTPUT_FLAG_PRIMARY\n"
    "      }\n"
    "    }\n"
    "    inputs {\n"
    "      primary {\n"
    "        sampling_rates 8000|16000|32000|44100|48000\n"
    "        channel_masks AUDIO_CHANNEL_IN_MONO|AUDIO_CHANNEL_IN_STEREO\n"
    "        formats AUDIO_FORMAT_PCM_16_BIT\n"
    "        devices AUDIO_DEVICE_IN_COMMUNICATION|AUDIO_DEVICE_IN_AMBIENT|AUDIO_DEVICE_IN_BUILTIN_MIC|AUDIO_DEVICE_IN_WIRED_HEADSET|AUDIO_DEVICE_IN_AUX_DIGITAL|AUDIO_DEVICE_IN_AUX_DIGITAL2|AUDIO_DEVICE_IN_VOICE_CALL|AUDIO_DEVICE_IN_BACK_MIC|AUDIO_DEVICE_IN_ALL_SCO|AUDIO_DEVICE_IN_FM|AUDIO_DEVICE_IN_DEFAULT\n"
    "      }\n"
    "    }\n"
    "  }\n"
    "  a2dp {\n"
    "    outputs {\n"
    "      a2dp {\n"
    "        sampling_rates 44100\n"
    "        channel_masks AUDIO_CHANNEL_OUT_STEREO\n"
    "        formats AUDIO_FORMAT_PCM_16_BIT\n"
    "        devices AUDIO_DEVICE_OUT_ALL_A2DP\n"
    "      }\n"
    "    }\n"
    "  }\n"
    "  usb {\n"
    "    outputs {\n"
    "       default {\n"
    "          sampling_rates 44100\n"
    "          channel_masks AUDIO_CHANNEL_OUT_STEREO\n"
    "          formats AUDIO_FORMAT_PCM_16_BIT\n"
    "          devices AUDIO_DEVICE_OUT_ALL_USB\n"
    "       }\n"
    "    }\n"
    "  }\n"
    "  r_submix {\n"
    "    outputs {\n"
    "      r_submix {\n"
    "        sampling_rates 44100|48000\n"
    "        channel_masks AUDIO_CHANNEL_OUT_STEREO\n"
    "        formats AUDIO_FORMAT_PCM_16_BIT\n"
    "        devices AUDIO_DEVICE_OUT_REMOTE_SUBMIX\n"
    "      }\n"
    "    }\n"
    "    inputs {\n"
    "      r_submix {\n"
    "        sampling_rates 44100|48000\n"
    "        channel_masks AUDIO_CHANNEL_IN_MONO|AUDIO_CHANNEL_IN_STEREO\n"
    "        formats AUDIO_FORMAT_PCM_16_BIT\n"
    "        devices AUDIO_DEVICE_IN_REMOTE_SUBMIX\n"
    "      }\n"
    "    }\n"
    "  }\n"
    "}\n"
    "\n";

static const char speaker_off_conf[] =
    "#\n"
    "# Audio policy configuration for generic device builds (goldfish audio HAL - emulator)\n"
    "#\n"
    "\n"
    "# Global configuration section: lists input and output devices always present on the device\n"
    "# as well as the output device selected by default.\n"
    "# Devices are designated by a string that corresponds to the enum in audio.h\n"
    "\n"
    "global_configuration {\n"
    "  attached_output_devices AUDIO_DEVICE_OUT_WIRED_HEADPHONE|AUDIO_DEVICE_OUT_ALL_A2DP\n"
    "  default_output_device AUDIO_DEVICE_OUT_WIRED_HEADPHONE\n"
    "  attached_input_devices AUDIO_DEVICE_IN_BUILTIN_MIC\n"
    "}\n"
    "\n"
    "# audio hardware module section: contains descriptors for all audio hw modules present on the\n"
    "# device. Each hw module node is named after the corresponding hw module library base name.\n"
    "# For instance, \"primary\" corresponds to audio.primary.<device>.so.\n"
    "# The \"primary\" module is mandatory and must include at least one output with\n"
    "# AUDIO_OUTPUT_FLAG_PRIMARY flag.\n"
    "# Each module descriptor contains one or more output profile descriptors and zero or more\n"
    "# input profile descriptors. Each profile lists all the parameters supported by a given output\n"
    "# or input stream category.\n"
    "# The \"channel_masks\", \"formats\", \"devices\" and \"flags\" are specified using strings corresponding\n"
    "# to enums in audio.h and audio_policy.h. They are concatenated by use of \"|\" without space or \"\\n\".\n"
    "\n"
    "audio_hw_modules {\n"
    "  primary {\n"
    "    outputs {\n"
    "      primary {\n"
    "        sampling_rates 44100\n"
    "        channel_masks AUDIO_CHANNEL_OUT_STEREO\n"
    "        formats AUDIO_FORMAT_PCM_16_BIT\n"
    "        devices AUDIO_DEVICE_OUT_WIRED_HEADSET|AUDIO_DEVICE_OUT_WIRED_HEADPHONE|AUDIO_DEVICE_OUT_ALL_SCO|AUDIO_DEVICE_OUT_DEFAULT\n"
    "        flags AUDIO_OUTPUT_FLAG_PRIMARY\n"
    "      }\n"
    "    }\n"
    "    inputs {\n"
    "      primary {\n"
    "        sampling_rates 8000|16000|32000|44100|48000\n"
    "        channel_masks AUDIO_CHANNEL_IN_MONO|AUDIO_CHANNEL_IN_STEREO\n"
    "        formats AUDIO_FORMAT_PCM_16_BIT\n"
    "        devices AUDIO_DEVICE_IN_COMMUNICATION|AUDIO_DEVICE_IN_AMBIENT|AUDIO_DEVICE_IN_BUILTIN_MIC|AUDIO_DEVICE_IN_WIRED_HEADSET|AUDIO_DEVICE_IN_AUX_DIGITAL|AUDIO_DEVICE_IN_AUX_DIGITAL2|AUDIO_DEVICE_IN_VOICE_CALL|AUDIO_DEVICE_IN_BACK_MIC|AUDIO_DEVICE_IN_ALL_SCO|AUDIO_DEVICE_IN_FM|AUDIO_DEVICE_IN_DEFAULT\n"
    "      }\n"
    "    }\n"
    "  }\n"
    "  a2dp {\n"
    "    outputs {\n"
    "      a2dp {\n"
    "        sampling_rates 44100\n"
    "        channel_masks AUDIO_CHANNEL_OUT_STEREO\n"
    "        formats AUDIO_FORMAT_PCM_16_BIT\n"
    "        devices AUDIO_DEVICE_OUT_ALL_A2DP\n"
    "      }\n"
    "    }\n"
    "  }\n"
    "  usb {\n"
    "    outputs {\n"
    "       default {\n"
    "          sampling_rates 44100\n"
    "          channel_masks AUDIO_CHANNEL_OUT_STEREO\n"
    "          formats AUDIO_FORMAT_PCM_16_BIT\n"
    "          devices AUDIO_DEVICE_OUT_ALL_USB\n"
    "       }\n"
    "    }\n"
    "  }\n"
    "  r_submix {\n"
    "    outputs {\n"
    "      r_submix {\n"
    "        sampling_rates 44100|48000\n"
    "        channel_masks AUDIO_CHANNEL_OUT_STEREO\n"
    "        formats AUDIO_FORMAT_PCM_16_BIT\n"
    "        devices AUDIO_DEVICE_OUT_REMOTE_SUBMIX\n"
    "      }\n"
    "    }\n"
    "    inputs {\n"
    "      r_submix {\n"
    "        sampling_rates 44100|48000\n"
    "        channel_masks AUDIO_CHANNEL_IN_MONO|AUDIO_CHANNEL_IN_STEREO\n"
    "        formats AUDIO_FORMAT_PCM_16_BIT\n"
    "        devices AUDIO_DEVICE_IN_REMOTE_SUBMIX\n"
    "      }\n"
    "    }\n"
    "  }\n"
    "}\n"
    "\n"
    "\n";

#endif